---
- name: dockers
  hosts: dockers
  vars_files:
  - config.yaml
  remote_user: ec2-user
  tasks:
  - name: start work
    shell: "./map_reduce.py -w -vv"
    args:
      chdir: "{{ repo_home }}/main"
